### ISSUE TITLE
Error on /b/  board (crash)

### ISSUE THREAD

**Issue by sasfmlzr** [Karasiq/webm-tv#4]
`
[ERROR] [08/04/2022 00:55:40.944] [webm-tv-akka.actor.default-dispatcher-4] [akka.stream.Log(akka://webm-tv/user/storeDispatcher/threadScanner/StreamSupervisor-1)] [2ch-json-api] Upstream failed.
upickle.Invalid$Json: jawn.ParseException: expected json value got < (line 1, column 1) (input: <html>
<head><title>303 See Other</title></head>
<body>
<center><h1>
303 See Other
</h1></center>
<hr><center>nginx</center>
</body>
</html>
)
	at upickle.json.package$.read(package.scala:11)
	at upickle.Types$class.read(Types.scala:156)
	at upickle.default$.read(Api.scala:25)
	at com.karasiq.webmtv.sosach.Json2chBoardApi$$anonfun$11.apply(Json2chBoardApi.scala:82)
	at com.karasiq.webmtv.sosach.Json2chBoardApi$$anonfun$11.apply(Json2chBoardApi.scala:82)
	at akka.stream.impl.fusing.Map$$anon$8.onPush(Ops.scala:42)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:594)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:619)
	at akka.actor.Actor$class.aroundReceive$$$capture(Actor.scala:484)
	at akka.actor.Actor$class.aroundReceive(Actor.scala)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage$$$capture(ActorCell.scala:526)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

**Comment by SirMaksimRuban** [comment]
Error 502 Ray ID: 73715d2d5ce5b785 • 2022-08-07 16:24:41 UTC
Bad gateway
